### ISSUE TITLE
[rmem] Unit Tests for Remote Memory Manager

### ISSUE THREAD

**Issue by EPodesta** [nanvix/multikernel#146]
# Description

The following unit tests should be introduced for the Remote Memory Manager.

## API Tests

- [x] Allocate and Free a Remote Memory Block
- [x] Write and Read to a Remote Memory Block

## Fault Injection Tests

- [x] Free an Invalid Remote Memory Block
- [x] Free a Bad Remote Memory Block
- [x] Read an Invalid Remote Memory Block
- [x] Read a Bad Remote Memory Block
- [x] Write to an Invalid Remote Memory Block
- [x] Write to a Bad Remote Memory Block

## Stress Tests

- [x] Allocate and Free Remote Memory Blocks Sequentially
- [x] Allocate and Free All Remote Memory Blocks
- [x] Allocate and Free Remote Memory Blocks Interleaved
- [x] Write and Read to/from Remote Memory Blocks Sequentially
- [x] Write and Read to/from Remote Memory Blocks Interleaved
- [x] Write and Read to/from All Remote Memory Blocks

# Updates

- Due to issue https://github.com/nanvix/multikernel/issues/155 fault injection tests for bad remote memory block reads/writes cannot be enabled.
- Feature introduced in commit 2d7fd763991e56bed5ef0910eb85d7eb2c688057.

**Comment by ppenna** [comment]
@EPodesta could you add the items to the list of API and Fault Injection tests?
