### ISSUE TITLE
[name] Name Resolution Fails with Man In the Middle

### ISSUE THREAD

**Issue by ppenna** [nanvix/multikernel#78]
**Description**

When using named mailboxes, a man in the middle attack is possible.

While the naming service client A is waiting a reply from the naming server, another (malicious) process may send a message to A to prevent the correctness of the name resolution protocol.

This bug may be tested by defining the `_TEST_MAN_IN_THE_MIDDLE` macro at compiling time.

**Solution**

Implement message buffering in the kernel.

**Comment by ppenna** [comment]
@joaovicentesouto and @joaofel-u  I guess that we can close this one, right?

**Comment by joaovicentesouto** [comment]
@ppenna Yeah, I suppose that with the exclusive use of a port by a service/client and the microkernel that manipulates the header and stores the message in a buffer, we guarantee peer-to-peer communication without interference.
